name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run checks
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build library
        run: bash build.sh
      - name: Run tests
        run: bash test/run_test.sh
